### ISSUE TITLE
Web page bench misleading

### ISSUE THREAD

**Issue by Dr-Emann** [plepers/Instagal#1]
At http://plepers.github.com/Instagal/#bench, the subtitle is 
"Instagal vs Adobe's AgalMiniAssembler"
Notice that Instagal is on the left, and Adobe is on the right.

In the actual benchmarks, the benchmarks are Adobe on the left, and Instagal on the right. This is confusing, and may lead a quick look at the title, then a run of the benchmarks to look like Adobe is the winner. Either flip the benchmarks, or the title, and it won't be a problem.

**Comment by plepers** [comment]
fixed
